name: CI

on:
  push:
    branches:
    - master
    - ci-cd-tests
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
    - master
    - ci-cd-tests
  workflow_dispatch:
      inputs:
        color:
          descriptions: 'Use color'
          required: true
          default: 'true'
        py-act:
          descriptions: 'Python 3.X for actions'
          required: false
          default: '3.7'
        pip_opts:
          description: Install options for pip
          required: false
          default: '--upgrade --upgrade-strategy eager'
env:
  ACIONS_SETUP_PY3: ${{ github.event.inputs.py-act || '3.7' }}
  PIP_INSTALL_OPTS: ${{ github.event.inputs.pip_opts || '--upgrade --upgrade-strategy eager' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint using pre-commit hooks
    steps:
      -
        name: Checkout repository
        id: checkout
        uses: actions/checkout@v2
      -
        name: Set up Python 3
        id: setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.ACIONS_SETUP_PY3 }}
      -
        name: Run pre-commit
        id: pre-commit
        uses: pre-commit/action@v2.0.0
        env:
          PRE_COMMIT_COLOR: ${{ github.event.inputs.color == 'false' && 'never' || 'always' }}

  tests:
    needs: lint
    runs-on: ${{ matrix.os }}
    name: "Test using Python ${{ matrix.py }} on ${{ matrix.os }}"
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        py: [3.6, 3.7]
    steps:
      -
        name: Checkout repository
        id: checkout
        uses: actions/checkout@v2
      -
        name: Set up Python ${{ matrix.py }}
        id: setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      -
        name: Set Python ${{ matrix.py }} cache
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-pydeps-${{ env.pythonLocation }}-${{ hashFiles('setup.cfg') }}-${{ hashFiles('pyproject.toml') }}
      -
        name : Install dependencies
        id: install-deps
        run: |
          python -m pip install --upgrade --upgrade-strategy eager pip setuptools
          python -m pip install --upgrade --upgrade-strategy eager tox tox-gh-actions coverage[toml]
      -
        name: Run tests on Python ${{ matrix.py }} via tox
        id: run-tox
        env:
          PY_COLORS: ${{ github.event.inputs.color == 'false' && 0 || 1 }}
        run: |
          python -m tox
      -
        name: Generate an XML report of coverage results
        id: cov-report-xml
        run: |
          python -m coverage xml
      -
        name: Upload coverage report to Codecov.io
        id: codecov-upload
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: ${{ secrets.ACTIONS_RUNNER_DEBUG }}
          fail_ci_if_error: true
